name: Issue Logger

on:
  issues:
    types: [opened, reopened]  # Runs when a new issue is created

jobs:
  log-issue:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push changes
      issues: write    # Required to modify issues

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Add "Internal" Label to Issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.issue.number,
            labels: ["Internal"]
          });

    - name: Create or Update Issue Log
      run: |
        touch logs/issue_log.txt  # Ensure file exists
        echo "Issue #${{ github.event.issue.number }} - ${{ github.event.issue.title }}" >> logs/issue_log.txt
        echo "${{ github.event.issue.body }}" >> logs/issue_log.txt
        echo "------------------------" >> logs/issue_log.txt

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Vineet Rana'
        git config --global user.email 'vineetrana2208@gmail.com'   # Use your GitHub email
        git add logs/issue_log.txt
        git commit -m "Log Issue #${{ github.event.issue.number }}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "Nothing to push"
