name: Increase GitHub Profile Views

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  visit-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Make an Authenticated Request to GitHub Profile
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" https://github.com/vineetranaji
