name: Run Python Code

on:
  schedule:
    - cron: '0 11 1 * *'   # Random day 1
    - cron: '0 11 3 * *'   # Random day 2
    - cron: '0 11 5 * *'   # Random day 3
    - cron: '0 11 7 * *'   # Random day 4
    - cron: '0 11 9 * *'   # Random day 5
    - cron: '0 11 11 * *'  # Random day 6
    - cron: '0 11 13 * *'  # Random day 7
    - cron: '0 11 15 * *'  # Random day 8
    - cron: '0 11 17 * *'  # Random day 9
    - cron: '0 11 19 * *'  # Random day 10
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the token has write permissions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: vineetranaji/python-day-to-day-code
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python scripts
      run: |
        mkdir -p logs
        echo "$(date '+%d %b %Y at %H:%M')" >> logs/output.log
        for script in tasks/*.py; do
          echo "Running $script" >> logs/output.log
          python "$script" >> logs/output.log 2>&1 || exit 1
        done

    - name: Commit and push logs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git stash
        git pull --rebase
        git stash pop
        git add -f logs/output.log
        git commit -m 'Add logs from GitHub Actions workflow' || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vineetranaji/github-workflows.git || echo "Nothing to push"