name: Run Python Code

on:
  schedule:
    - cron: '0 11 1 * *'   # Random day 1
    - cron: '0 11 3 * *'   # Random day 2
    - cron: '0 11 5 * *'   # Random day 3
    - cron: '0 11 7 * *'   # Random day 4
    - cron: '0 11 9 * *'   # Random day 5
    - cron: '0 11 11 * *'  # Random day 6
    - cron: '0 11 13 * *'  # Random day 7
    - cron: '0 11 15 * *'  # Random day 8
    - cron: '0 11 17 * *'  # Random day 9
    - cron: '0 11 19 * *'  # Random day 10
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the token has write permissions

    steps:
    - name: Checkout python-day-to-day-code repository
      uses: actions/checkout@v2
      with:
        repository: vineetranaji/python-day-to-day-code
        path: python-day-to-day-code
        token: ${{ secrets.GITHUB_TOKEN }}
      # This step checks out the python-day-to-day-code repository

    - name: Install dependencies
      run: pip install -r github-workflows/logs/requirements.txt
      
    - name: Checkout github-workflows repository
      uses: actions/checkout@v2
      with:
        repository: vineetranaji/github-workflows
        path: github-workflows
        token: ${{ secrets.GITHUB_TOKEN }}
      # This step checks out the github-workflows repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
      # This step sets up the Python environment

    - name: Run Python scripts
      run: |
        mkdir -p github-workflows/logs
        echo "$(date '+%d %b %Y at %H:%M')" >> github-workflows/logs/output.log
        for script in python-day-to-day-code/tasks/*.py; do
          echo "Running $script" >> github-workflows/logs/output.log
          python "$script" >> github-workflows/logs/output.log 2>&1 || exit 1
        done
      # This step runs the Python scripts and logs the output

    - name: Commit and push logs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd github-workflows
        git config --global user.name 'Vineet Rana'
        git config --global user.email 'vineetrana2208@gmail.com'  # Use your GitHub email
        git add -f logs/output.log
        git commit -m 'Add logs from GitHub Actions workflow' || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vineetranaji/github-workflows.git || echo "Nothing to push"
      # This step commits and pushes the logs to the github-workflows repository
