name: Terraform Validation

on:
  schedule:
    - cron: '0 01 1 * *'
    - cron: '0 12 4 * *'
    - cron: '0 14 5 * *'
    - cron: '0 12 6 * *'
    - cron: '0 12 9 * *'
    - cron: '30 11 10 * *'
    - cron: '0 12 13 * *'
    - cron: '0 12 17 * *'
    - cron: '30 11 18 * *'
    - cron: '45 11 19 * *'
    - cron: '07 11 20 * *'
    - cron: '08 11 25 * *'
    - cron: '09 11 28 * *'
    - cron: '01 11 29 * *'
  workflow_dispatch:

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
    - name: Checkout Terraform Repository
      uses: actions/checkout@v4
      with:
        repository: vineetranaji/Terraform-day-to-day-Code
        path: Terraform-day-to-day-Code
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout github-workflows Repository
      uses: actions/checkout@v4
      with:
        repository: vineetranaji/github-workflows
        path: github-workflows
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.6.0'

    - name: Run Terraform Validate
      run: |
        mkdir -p github-workflows/logs
        echo "$(date '+%d %b %Y at %H:%M')" >> github-workflows/logs/terraform-output.log
        #log_file="github-workflows/logs/terraform-output.log"
        #err_log="github-workflows/logs/terraform-output.log"
        
        echo "Terraform Validation started at $(date '+%d %b %Y %H:%M:%S')" >> "github-workflows/logs/terraform-output.log"

        #cd Terraform-day-to-day-Code
        #terraform init -backend=false >> "github-workflows/logs/terraform-output.log" 2>> "github-workflows/logs/terraform-output.log"
        terraform validate >> "github-workflows/logs/terraform-output.log" 2>> "github-workflows/logs/terraform-output.log"

        echo "Validation completed at $(date '+%d %b %Y %H:%M:%S')" >> "github-workflows/logs/terraform-output.log"
        
    - name: Commit and Push Logs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd github-workflows
        git config --global user.name 'Vineet Rana'
        git config --global user.email 'vineetrana2208@gmail.com'
        git add -f logs/terraform-output.log
        git commit -m "Terraform Validation Logs from GitHub Actions on $(date '+%Y-%m-%d')" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vineetranaji/github-workflows.git || echo "Nothing to push"
