name: Terraform Validation

on:
  schedule:
    - cron: '0 11 1 * *'
    - cron: '0 11 4 * *'
    - cron: '0 11 5 * *'
    - cron: '0 11 6 * *'
    - cron: '0 11 9 * *'
    - cron: '0 11 10 * *'
    - cron: '0 11 13 * *'
    - cron: '0 11 17 * *'
    - cron: '0 11 18 * *'
    - cron: '0 11 19 * *'
    - cron: '0 11 20 * *'
    - cron: '0 11 25 * *'
    - cron: '0 11 28 * *'
    - cron: '0 11 29 * *'
  workflow_dispatch:

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
    - name: Checkout Terraform Repository
      uses: actions/checkout@v4
      with:
        repository: vineetranaji/Terraform-day-to-day-Code
        path: Terraform-day-to-day-Code
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout github-workflows Repository
      uses: actions/checkout@v4
      with:
        repository: vineetranaji/github-workflows
        path: github-workflows
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.6.0'

    - name: Run Terraform Validate
      run: |
        #mkdir -p github-workflows/logs
        log_file="github-workflows/logs/terraform-output.log"
        err_log="github-workflows/logs/terraform-output.log"
        
        echo "Terraform Validation started at $(date '+%d %b %Y %H:%M:%S')" > "$log_file"

        #cd Terraform-day-to-day-Code
        #terraform init -backend=false >> "$log_file" 2>> "$err_log"
        terraform validate -json >> "$log_file" 2>> "$err_log"

        echo "Validation completed at $(date '+%d %b %Y %H:%M:%S')" >> "$log_file"
        
    - name: Commit and Push Logs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd github-workflows
        git config --global user.name 'Vineet Rana'
        git config --global user.email 'vineetrana2208@gmail.com'
        git add -f logs/terraform-output.log
        if git status | grep -q 'Changes to be committed'; then
          git commit -m "Terraform Validation Logs from GitHub Actions on $(date '+%Y-%m-%d')"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vineetranaji/github-workflows.git
        else
          echo "No changes to commit"
        fi
